[project]
name = "stacksone-vault-v7"
description = "StacksOne Vault V7"
authors = []
telemetry = true
cache_dir = "./.cache"

[contracts.chaintap]
path = 'contracts/chaintap.clar'
clarity_version = 2
epoch = 2.5
